"""
Script to help find and document sources for gas and carbon prices.
"""

print("=" * 80)
print("FINDING SOURCES FOR GAS AND CARBON PRICES")
print("=" * 80)

print("\n1. GAS PRICE (£50/MWh)")
print("-" * 80)
print("Current value: £50/MWh (calibrated for 2025)")
print("\nWhere to find actual 2025 data:")
print("  - NBP (National Balancing Point) gas prices: ICE (Intercontinental Exchange)")
print("  - DESNZ Energy Trends: https://www.gov.uk/government/collections/energy-trends")
print("  - Conversion: NBP prices in pence/therm need conversion to £/MWh")
print("    - 1 therm = 29.3 kWh = 0.0293 MWh")
print("    - For electricity generation, also need heat rate (~50% efficiency)")
print("    - Rough conversion: 1 p/therm ≈ £0.34/MWh (at 50% efficiency)")
print("\n2024 reference:")
print("  - validation_2024.py shows: £27.0/MWh (Q3 2024, 2.7p/kWh)")
print("  - This was actual 2024 data from DESNZ/BEIS")
print("\n2025 estimate:")
print("  - £50/MWh was calibrated to match expected £75/MWh wholesale price")
print("  - Need to verify against actual 2025 NBP prices")
print("  - Check: ICE NBP daily prices, DESNZ quarterly energy prices")

print("\n2. CARBON PRICE (£60/tonne CO₂)")
print("-" * 80)
print("Current value: £60/tonne CO₂ (marked as '2025 typical')")
print("\nWhere to find actual 2025 data:")
print("  - UK ETS (Emissions Trading Scheme) prices: ICE, EEX, or DESNZ")
print("  - DESNZ publishes UK ETS statistics")
print("  - UK ETS price data: https://www.gov.uk/government/collections/uk-emissions-trading-scheme-uk-ets")
print("\n2024 reference:")
print("  - validation_2024.py shows: £50.0/tonne CO₂ (UK ETS average 2024)")
print("  - This was actual 2024 data")
print("\n2025 estimate:")
print("  - £60/tonne is an assumption (20% increase from 2024)")
print("  - Need to verify against actual 2025 UK ETS prices")
print("  - UK ETS prices are publicly available from ICE or DESNZ")

print("\n3. CONVERSION NOTES")
print("-" * 80)
print("Gas price conversion (NBP to electricity generation cost):")
print("  - NBP prices are typically quoted in pence per therm (p/therm)")
print("  - 1 therm = 29.3 kWh = 0.0293 MWh")
print("  - For CCGT: heat rate ~7,000 BTU/kWh = ~50% efficiency")
print("  - To generate 1 MWh electricity, need ~2 MWh thermal = ~68 therms")
print("  - Conversion: p/therm × 0.68 ≈ £/MWh (rough)")
print("\nExample:")
print("  - If NBP = 50 p/therm")
print("  - Electricity generation cost ≈ 50 × 0.68 ≈ £34/MWh")
print("  - (This is simplified - actual depends on plant efficiency)")

print("\n4. RECOMMENDED DATA SOURCES")
print("-" * 80)
print("For Gas Prices:")
print("  1. DESNZ Energy Trends (quarterly):")
print("     https://www.gov.uk/government/collections/energy-trends")
print("  2. ICE NBP daily prices:")
print("     https://www.theice.com/products/27996665/UK-Natural-Gas-Futures")
print("  3. BEIS/DESNZ quarterly energy prices publication")
print("\nFor Carbon Prices:")
print("  1. UK ETS statistics (DESNZ):")
print("     https://www.gov.uk/government/collections/uk-emissions-trading-scheme-uk-ets")
print("  2. ICE UK ETS prices:")
print("     https://www.theice.com/products/6681985/UK-Emissions-Allowance-Futures")
print("  3. EEX UK ETS prices")

print("\n5. NEXT STEPS")
print("-" * 80)
print("1. Download actual 2025 NBP gas prices from ICE or DESNZ")
print("2. Download actual 2025 UK ETS carbon prices")
print("3. Convert NBP prices to £/MWh for electricity generation")
print("4. Update model defaults with actual data")
print("5. Document sources in code comments and VALIDATION_2025.md")

print("\n" + "=" * 80)
print("NOTE: The £50/MWh and £60/tonne values are currently:")
print("  - £50/MWh: Calibrated to match 2025 wholesale prices (not from actual gas data)")
print("  - £60/tonne: Assumed 20% increase from 2024 (£50/tonne)")
print("=" * 80)

